#NAME: Yash Moondhra
#EMAIL: ymoondhra@gmail.com
#ID: 123456789
default:
	gcc -Wall -Wextra lab1a.c -o lab1a
clean:
	rm -f lab1a-123456789.tar.gz lab1a
dist:
	tar -cvzf lab1a-123456789.tar.gz lab1a.c README Makefile
