#NAME: Yash Moondhra
#EMAIL: ymoondhra@gmail.com
#ID: 123456789
default:
	gcc -Wall -Wextra lab1b-client.c -lz -o lab1b-client
	gcc -Wall -Wextra lab1b-server.c -lz -o lab1b-server
clean:
	rm -f lab1b-123456789.tar.gz lab1b-client lab1b-server
dist:
	tar -cvzf lab1b-123456789.tar.gz lab1b-client.c lab1b-server.c README Makefile
