#NAME: Yash Moondhra
#EMAIL: ymoondhra@gmail.com
#ID: 123456789
clean:
	rm -f lab4a-123456789.tar.gz 
dist:
	tar -cvzf lab4a-123456789.tar.gz README Makefile my_beaglebone.jpg connected.png copy.png build_run.png git.png