#!/bin/bash

find_utf()
{
    for var in "$@"
    do
        if [[ -d $var ]]; then
	    cd $var
	    find_utf $(ls)
	    cd ..
	else
	    if file -b $var | grep -c -q "UTF-8";  then
		line=$(head -n 1 $var)
		if [ "$line" == "-*- coding: utf-8 -*-" ]; then
		    continue
		else
		   echo $var
                fi		
	    fi
        fi
    done
}

find_utf "$@"
